jerryc-jpg/MeowMarket

server/api/product.js, server/app.js, server/db/Product.js, server/db/index.js
=> update db api

src/Components/About.js, src/Components/App.js, src/Components/Navbar.js
=> Added About Us

src/Components/Cart.js, src/Components/singleProduct.js, src/store/cart.js
=> update add to cart feature

server/db/Product.js, server/db/index.js
=> Update products db

src/Components/Navbar.js, static/index.html
Update logo, center the anchors, and login button align to right end
=> Navbar style

src/Components/Navbar.js, static/styles.css
=> Updated Navbar

src/Components/Admin.js, src/Components/AllCats.js, src/Components/Home.js
updated all cats component style
=> Updated style

src/Components/Home.js, src/Components/Navbar.js
=> Update Home Page

src/Components/App.js, src/Components/Cart.js, src/Components/Register.js, src/store/auth.js
we are missing the logout button with the logged in user showing
=> seperate route for register

src/Components/AllAccess.js, src/Components/Home.js
add allcats and all access tabs at home page
=> allcats and all access tabs

src/Components/AllAccess.js, src/Components/AllCats.js, src/Components/Home.js
=> Updated All Cats

src/Components/App.js, src/Components/Navbar.js
added routes to profile add app.js && added linked to profile at nav bar
=> Added Link to profile

src/Components/App.js, src/Components/Navbar.js, src/Components/Orders.js
created Orders component, added route to Orders
=> Orders component

src/Components/About.js, src/Components/Navbar.js, static/styles.css
nav bar now sticks to the top, and fixed about page screen size bug
=> Fixed nav-bar

src/Components/Cart.js, static/styles.css
=> Updated Cart

src/Components/Cart.js, src/Components/singleProduct.js, src/store/cart.js
updated cart function, the +- at both Cart and SingleProduct component
=> updated the cart function

src/Components/Navbar.js, static/styles.css
=> updated cart icon

src/Components/AllCats.js
=> add pagination function

package-lock.json, package.json, src/Components/AllAccess.js, src/Components/AllCats.js
Imported react toastify, added notification to user when item added to cart
=> Updated notification

src/Components/Profile.js, static/styles.css
Updated style for the profile page
=> Updated Profile Page

src/Components/Navbar.js
navigate to home page after logged out
=> Updated logout functionality

src/Components/App.js, src/Components/Navbar.js, src/Components/Team.js, static/index.html, static/styles.css
Created team page, team members image, title, and links to github and linkedin
=> Created Team Page
